create table matchinfo (
  league varchar(6),
  year varchar(4),
  season varchar(6),
  type varchar(15),
  blueTeamTag varchar(10),
  bResult tinyint,
  rResult tinyint,
  redTeamTag varchar(10),
  gamelength tinyint,
  blueTop varchar(20),
  blueTopChamp varchar(20),
  blueJungle varchar(20),
  blueJungleChamp varchar(20),
  blueMiddle varchar(20),
  blueMiddleChamp varchar(20),
  blueADC varchar(20),
  blueADCChamp varchar(20),
  blueSupport varchar(20),
  blueSupportChamp varchar(20),
  redTop varchar(20),
  redTopChamp varchar(20),
  redJungle varchar(20),
  redJungleChamp varchar(20),
  redMiddle varchar(20),
  redMiddleChamp varchar(20),
  redADC varchar(20),
  redADCChamp varchar(20),
  redSupport varchar(20),
  redSupportChamp varchar(20),
  address varchar(150),
  primary key (address)
);